# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb10cfa92f349962d4a5348abeb5070abb801ce1aba7c52cede4df07cb51d6ef4d6ce831f882d9995e6e1b6f626786f6fe6849672fcef24da8569c8a10d53f66

test:
  secret_key_base: b1a1942da1afc547f898aecae38871b09b0361aa5462a67f9edea612834d5ee4100d356c60cdd176d42aaca2ef5aca652ce9ac02a1dc0e0b203fbedb84f27af6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
